In [1]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

In [11]:
url=['https://www.imdb.com/search/title/?groups=top_250&sort=user_rating,desc&ref_=adv_prv','https://www.imdb.com/search/title/?groups=top_250&sort=user_rating,desc&start=51&ref_=adv_nxt','https://www.imdb.com/search/title/?groups=top_250&sort=user_rating,desc&start=101&ref_=adv_nxt','https://www.imdb.com/search/title/?groups=top_250&sort=user_rating,desc&start=151&ref_=adv_nxt','https://www.imdb.com/search/title/?groups=top_250&sort=user_rating,desc&start=201&ref_=adv_nxt']

In [12]:
#taking the urls into a page from the server
page=[]
for i in url:
    page.append(requests.get(i))

In [13]:
#now using beautifulsoup
soup=[]
for i in page:
    soup.append(BeautifulSoup(i.text,'html.parser'))

In [19]:
#determining the ID
id_text=[]
id=[]
for i in soup:
    id_text.append(i.find_all(class_='lister-item-index unbold text-primary'))
for item in id_text:
    for i in item:
        id.append(i.text)

In [22]:
#determining the titles of the movies
title_text=[]
title=[]
for i in soup:
    title_text.append(i.find_all('h3',{'class':'lister-item-header'}))
for item in title_text:
    for i in item:
        title.append(i.find('a').text)

In [24]:
len(title)

250

In [25]:
#determining the Release years of the movies
Release_year_text=[]
Release_year=[]
for i in soup:
    Release_year_text.append(i.find_all(class_='lister-item-year text-muted unbold'))
for item in Release_year_text:
    for i in item:
        Release_year.append(i.text)

In [27]:
len(Release_year)

250

In [28]:
#determining the runtimes of the movies
runtime=[]
runtime_text=[]
for i in soup:
    runtime_text.append(i.find_all(class_='runtime'))
for item in runtime_text:
    for i in item:
        runtime.append(i.text)

In [30]:
len(runtime)

250

In [31]:
#determining the genres of the movies
genre=[]
genre_text=[]
for i in soup:
    genre_text.append(i.find_all(class_='genre'))
for item in genre_text:
    for i in item:
        genre.append(i.text)
for i,j in enumerate(genre):
    genre[i]=j.replace('\n','').strip()

In [33]:
len(genre)

250

In [35]:
#determining the ratings of the movies
rating_text=[]
rating=[]
for i in soup:
    rating_text.append(i.find_all('div',{'class':'inline-block ratings-imdb-rating'}))
for item in rating_text:
    for i in item:
        rating.append(i.text)
for i,j in enumerate(rating):
    rating[i]=j.replace('\n','').strip()

In [36]:
len(rating)

250

In [107]:
#determining the descriptions of the movies
description_text=[]
for i in soup:
    description_text.append(i.find_all('p',{'class':'text-muted'}))
description=[]
for item in description_text:
    for i in item:
        description.append(i.text)
d=[]
for i in range(len(description)):
    if(int(i)%2!=0):
        d.append(description[i])
for i,j in enumerate(d):
    d[i]=j.replace('\n','').strip()

In [108]:
about=d

In [83]:
#determining the directors of the movies
director_text=[]
for i in soup:
    director_text.append(i.find_all('p',{'class':''}))
director_star=[]
for item in director_text:
    for i in item:
        if 'Director' in i.text:
             director_star.append(i.text)
director=[]
for i in range(len(director_star)):
    director.append(director_star[i].split("Stars:")[0])
for i,j in enumerate(director):
    director[i]=j.replace('\n','').strip()
for i,j in enumerate(director):
    director[i]=j.replace('|','').strip()
for i,j in enumerate(director):
    director[i]=j.replace('Director:','').strip()

In [85]:
len(director)

250

In [86]:
#determininng the stars of the movies
stars=[]
for i in range(len(director_star)):
    stars.append(director_star[i].split("Stars:")[1])
for i,j in enumerate(stars):
    stars[i]=j.replace('\n','').strip()

In [88]:
len(stars)

250

In [89]:
#determining the votes of the movies
votes_gross_text=[]
for i in soup:
    votes_gross_text.append(i.find_all(class_='sort-num_votes-visible'))
votes_gross=[]
for item in votes_gross_text:
    for i in item:
        votes_gross.append(i.text)
votes=[]
for i in range(len(votes_gross)):
    votes.append(votes_gross[i].split("|")[0])
for i,j in enumerate(votes):
    votes[i]=j.replace('\n','').strip()
for i,j in enumerate(votes):
    votes[i]=j.replace('Votes:','').strip()

In [91]:
len(votes)

250

In [94]:
#determining the gross of the movies
gross=[]
for i in range(len(votes_gross)):
    if(len(votes_gross[i].split("|"))==2):
        gross.append(votes_gross[i].split("|")[1])
    else:
        gross.append(None)
for i,j in enumerate(gross):
    if(gross[i]!=None):
        gross[i]=j.replace('\n','').strip()
for i,j in enumerate(gross):
    if(gross[i]!=None):
        gross[i]=j.replace('Gross:','').strip()

In [95]:
len(gross)

250

In [110]:
final_array=[]
for i,ti,re,ru,g,ra,de,di,st,vo,gr in zip(id,title,Release_year,runtime,genre,rating,about,director,stars,votes,gross):
    final_array.append({'ID':i,'TITLE':ti,'RELEASE YEAR':re,'RUN TIME':ru,'GENRE':g,'RATING':ra,'DESCRIPTION':de,'DIRECTOR':di,'STARS':st,'VOTES':vo,'GROSS':gr})

In [111]:
#converting to datafame
data=pd.DataFrame(final_array)

In [112]:
data=data[['ID','TITLE','RELEASE YEAR','RUN TIME','GENRE','RATING','DESCRIPTION','DIRECTOR','STARS','VOTES','GROSS']]

In [113]:
data.shape

(250, 11)

In [114]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 11 columns):
ID              250 non-null object
TITLE           250 non-null object
RELEASE YEAR    250 non-null object
RUN TIME        250 non-null object
GENRE           250 non-null object
RATING          250 non-null object
DESCRIPTION     250 non-null object
DIRECTOR        250 non-null object
STARS           250 non-null object
VOTES           250 non-null object
GROSS           217 non-null object
dtypes: object(11)
memory usage: 21.6+ KB

In [115]:
data

,ID,TITLE,RELEASE YEAR,RUN TIME,GENRE,RATING,DESCRIPTION,DIRECTOR,STARS,VOTES,GROSS
0,1.,The Shawshank Redemption,(1994),142 min,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...","2,124,114",$28.34M
1,2.,The Godfather,(1972),175 min,"Crime, Drama",9.2,The aging patriarch of an organized crime dyna...,Francis Ford Coppola,"Marlon Brando, Al Pacino, James Caan, Diane Ke...","1,458,425",$134.97M
2,3.,The Dark Knight,(2008),152 min,"Action, Crime, Drama",9.0,When the menace known as The Joker emerges fro...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...","2,089,225",$534.86M
3,4.,The Godfather: Part II,(1974),202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,"Al Pacino, Robert De Niro, Robert Duvall, Dian...","1,014,344",$57.30M
4,5.,The Lord of the Rings: The Return of the King,(2003),201 min,"Adventure, Drama, Fantasy",8.9,Gandalf and Aragorn lead the World of Men agai...,Peter Jackson,"Elijah Wood, Viggo Mortensen, Ian McKellen, Or...","1,511,314",$377.85M
5,6.,Pulp Fiction,(1994),154 min,"Crime, Drama",8.9,"The lives of two mob hitmen, a boxer, a gangst...",Quentin Tarantino,"John Travolta, Uma Thurman, Samuel L. Jackson,...","1,663,945",$107.93M
6,7.,Schindler's List,(1993),195 min,"Biography, Drama, History",8.9,"In German-occupied Poland during World War II,...",Steven Spielberg,"Liam Neeson, Ralph Fiennes, Ben Kingsley, Caro...","1,102,227",$96.90M
7,8.,12 Angry Men,(1957),96 min,Drama,8.9,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,"Henry Fonda, Lee J. Cobb, Martin Balsam, John ...","604,955",$4.36M
8,9.,Inception,(2010),148 min,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...","1,862,363",$292.58M
9,10.,Fight Club,(1999),139 min,Drama,8.8,An insomniac office worker and a devil-may-car...,David Fincher,"Brad Pitt, Edward Norton, Meat Loaf, Zach Grenier","1,697,825",$37.03M
10,11.,The Lord of the Rings: The Fellowship of the Ring,(2001),178 min,"Adventure, Drama, Fantasy",8.8,A meek Hobbit from the Shire and eight compani...,Peter Jackson,"Elijah Wood, Ian McKellen, Orlando Bloom, Sean...","1,526,869",$315.54M
11,12.,Forrest Gump,(1994),142 min,"Drama, Romance",8.8,"The presidencies of Kennedy and Johnson, the e...",Robert Zemeckis,"Tom Hanks, Robin Wright, Gary Sinise, Sally Field","1,633,438",$330.25M
12,13.,"Il buono, il brutto, il cattivo",(1966),161 min,Western,8.8,A bounty hunting scam joins two men in an unea...,Sergio Leone,"Clint Eastwood, Eli Wallach, Lee Van Cleef, Al...","630,959",$6.10M
13,14.,The Lord of the Rings: The Two Towers,(2002),179 min,"Adventure, Drama, Fantasy",8.7,While Frodo and Sam edge closer to Mordor with...,Peter Jackson,"Elijah Wood, Ian McKellen, Viggo Mortensen, Or...","1,366,766",$342.55M
14,15.,The Matrix,(1999),136 min,"Action, Sci-Fi",8.7,A computer hacker learns from mysterious rebel...,"Directors:Lana Wachowski, Lilly Wachowski","Keanu Reeves, Laurence Fishburne, Carrie-Anne ...","1,527,989",$171.48M
15,16.,Goodfellas,(1990),146 min,"Biography, Crime, Drama",8.7,The story of Henry Hill and his life in the mo...,Martin Scorsese,"Robert De Niro, Ray Liotta, Joe Pesci, Lorrain...","917,574",$46.84M
16,17.,Star Wars: Episode V - The Empire Strikes Back,(1980),124 min,"Action, Adventure, Fantasy",8.7,After the Rebels are brutally overpowered by t...,Irvin Kershner,"Mark Hamill, Harrison Ford, Carrie Fisher, Bil...","1,063,684",$290.48M
17,18.,One Flew Over the Cuckoo's Nest,(1975),133 min,Drama,8.7,A criminal pleads insanity after getting into ...,Milos Forman,"Jack Nicholson, Louise Fletcher, Will Sampson,...","840,772",$112.00M
18,19.,Avengers: Endgame,(2019),181 min,"Action, Adventure, Sci-Fi",8.6,After the devastating events of Avengers: Infi...,"Directors:Anthony Russo, Joe Russo","Robert Downey Jr., Chris Evans, Mark Ruffalo, ...","523,997",$858.04M
19,20.,Interstellar,(2014),169 min,"Adventure, Drama, Sci-Fi",8.6,A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...","1,319,428",$188.02M
20,21.,Cidade de Deus,(2002),130 min,"Crime, Drama",8.6,"In the slums of Rio, two kids' paths diverge a...","Directors:Fernando Meirelles, Kátia Lund","Alexandre Rodrigues, Leandro Firmino, Matheus ...","651,215",$7.56M
21,22.,Sen to Chihiro no kamikakushi,(2001),125 min,"Animation, Adventure, Family",8.6,"During her family's move to the suburbs, a sul...","Directors:Hayao Miyazaki, Kirk Wise","Daveigh Chase, Suzanne Pleshette, Miyu Irino, ...","566,522",$10.06M
22,23.,Saving Private Ryan,(1998),169 min,"Drama, War",8.6,"Following the Normandy Landings, a group of U....",Steven Spielberg,"Tom Hanks, Matt Damon, Tom Sizemore, Edward Burns","1,125,293",$216.54M
23,24.,The Green Mile,(1999),189 min,"Crime, Drama, Fantasy",8.6,The lives of guards on Death Row are affected ...,Frank Darabont,"Tom Hanks, Michael Clarke Duncan, David Morse,...","1,030,425",$136.80M
24,25.,La vita è bella,(1997),116 min,"Comedy, Drama, Romance",8.6,When an open-minded Jewish librarian and his s...,Roberto Benigni,"Roberto Benigni, Nicoletta Braschi, Giorgio Ca...","560,634",$57.60M
25,26.,Se7en,(1995),127 min,"Crime, Drama, Mystery",8.6,"Two detectives, a rookie and a veteran, hunt a...",David Fincher,"Morgan Freeman, Brad Pitt, Kevin Spacey, Andre...","1,304,507",$100.13M
26,27.,Léon,(1994),110 min,"Action, Crime, Drama",8.6,"Mathilda, a 12-year-old girl, is reluctantly t...",Luc Besson,"Jean Reno, Gary Oldman, Natalie Portman, Danny...","938,571",$19.50M
27,28.,The Silence of the Lambs,(1991),118 min,"Crime, Drama, Thriller",8.6,A young F.B.I. cadet must receive the help of ...,Jonathan Demme,"Jodie Foster, Anthony Hopkins, Lawrence A. Bon...","1,149,590",$130.74M
28,29.,Star Wars,(1977),121 min,"Action, Adventure, Fantasy",8.6,Luke Skywalker joins forces with a Jedi Knight...,George Lucas,"Mark Hamill, Harrison Ford, Carrie Fisher, Ale...","1,132,690",$322.74M
29,30.,Shichinin no samurai,(1954),207 min,"Adventure, Drama",8.6,A poor village under attack by bandits recruit...,Akira Kurosawa,"Toshirô Mifune, Takashi Shimura, Keiko Tsushim...","287,852",$0.27M
...,...,...,...,...,...,...,...,...,...,...,...
220,221.,Platoon,(1986),120 min,"Drama, War",8.1,A young soldier in Vietnam faces a moral crisi...,Oliver Stone,"Charlie Sheen, Tom Berenger, Willem Dafoe, Kei...","354,638",$138.53M
221,222.,"Paris, Texas",(1984),145 min,Drama,8.1,"Travis Henderson, an aimless drifter who has b...",Wim Wenders,"Harry Dean Stanton, Nastassja Kinski, Dean Sto...","76,148",$2.18M
222,223.,Kaze no tani no Naushika,(1984),117 min,"Animation, Adventure, Fantasy",8.1,Warrior and pacifist Princess Nausicaä despera...,Hayao Miyazaki,"Sumi Shimamoto, Mahito Tsujimura, Hisako Kyôda...","129,781",$0.50M
223,224.,The Thing,(1982),109 min,"Horror, Mystery, Sci-Fi",8.1,A research team in Antarctica is hunted by a s...,John Carpenter,"Kurt Russell, Wilford Brimley, Keith David, Ri...","335,470",$13.78M
224,225.,Blade Runner,(1982),117 min,"Action, Sci-Fi, Thriller",8.1,A blade runner must pursue and terminate four ...,Ridley Scott,"Harrison Ford, Rutger Hauer, Sean Young, Edwar...","635,374",$32.87M
225,226.,The Elephant Man,(1980),124 min,"Biography, Drama",8.1,A Victorian surgeon rescues a heavily disfigur...,David Lynch,"Anthony Hopkins, John Hurt, Anne Bancroft, Joh...","202,239",None
226,227.,Life of Brian,(1979),94 min,Comedy,8.1,Born on the original Christmas in the stable n...,Terry Jones,"Graham Chapman, John Cleese, Michael Palin, Te...","338,055",$20.05M
227,228.,The Deer Hunter,(1978),183 min,"Drama, War",8.1,An in-depth examination of the ways in which t...,Michael Cimino,"Robert De Niro, Christopher Walken, John Cazal...","286,879",$48.98M
228,229.,Rocky,(1976),120 min,"Drama, Sport",8.1,A small-time boxer gets a supremely rare chanc...,John G. Avildsen,"Sylvester Stallone, Talia Shire, Burt Young, C...","477,690",$117.24M
229,230.,Network,(1976),121 min,Drama,8.1,A television network cynically exploits a dera...,Sidney Lumet,"Faye Dunaway, William Holden, Peter Finch, Rob...","132,795",None
230,231.,Barry Lyndon,(1975),185 min,"Adventure, Drama, History",8.1,An Irish rogue wins the heart of a rich widow ...,Stanley Kubrick,"Ryan O'Neal, Marisa Berenson, Patrick Magee, H...","134,072",None
231,232.,Cool Hand Luke,(1967),127 min,"Crime, Drama",8.1,A laid back Southern man is sentenced to two y...,Stuart Rosenberg,"Paul Newman, George Kennedy, Strother Martin, ...","150,167",None
232,233.,Persona,(1966),85 min,"Drama, Thriller",8.1,A nurse is put in charge of a mute actress and...,Ingmar Bergman,"Bibi Andersson, Liv Ullmann, Margaretha Krook,...","88,425",None
233,234.,La battaglia di Algeri,(1966),121 min,"Drama, War",8.1,"In the 1950s, fear and violence escalate as th...",Gillo Pontecorvo,"Brahim Hadjadj, Jean Martin, Yacef Saadi, Tomm...","47,430",$0.06M
234,235.,Les quatre cents coups,(1959),99 min,"Crime, Drama",8.1,"A young boy, left without attention, delves in...",François Truffaut,"Jean-Pierre Léaud, Albert Rémy, Claire Maurier...","93,356",None
235,236.,Ben-Hur,(1959),212 min,"Adventure, Drama, History",8.1,When a Jewish prince is betrayed and sent into...,William Wyler,"Charlton Heston, Jack Hawkins, Stephen Boyd, H...","203,312",$74.70M
236,237.,The Bridge on the River Kwai,(1957),161 min,"Adventure, Drama, War",8.1,After settling his differences with a Japanese...,David Lean,"William Holden, Alec Guinness, Jack Hawkins, S...","187,832",$44.91M
237,238.,On the Waterfront,(1954),108 min,"Crime, Drama, Thriller",8.1,An ex-prize fighter turned longshoreman strugg...,Elia Kazan,"Marlon Brando, Karl Malden, Lee J. Cobb, Rod S...","130,150",$9.60M
238,239.,Le salaire de la peur,(1953),131 min,"Adventure, Drama, Thriller",8.1,"In a decrepit South American village, four men...",Henri-Georges Clouzot,"Yves Montand, Charles Vanel, Peter van Eyck, F...","48,833",None
239,240.,The Third Man,(1949),104 min,"Film-Noir, Mystery, Thriller",8.1,Pulp novelist Holly Martins travels to shadowy...,Carol Reed,"Orson Welles, Joseph Cotten, Alida Valli, Trev...","146,630",$0.45M
240,241.,Rebecca,(1940),130 min,"Drama, Mystery, Romance",8.1,A self-conscious woman juggles adjusting to he...,Alfred Hitchcock,"Laurence Olivier, Joan Fontaine, George Sander...","111,958",$4.36M
241,242.,Mr. Smith Goes to Washington,(1939),129 min,"Comedy, Drama",8.1,A naive man is appointed to fill a vacancy in ...,Frank Capra,"James Stewart, Jean Arthur, Claude Rains, Edwa...","99,157",$9.60M
242,243.,Gone with the Wind,(1939),238 min,"Drama, History, Romance",8.1,A manipulative woman and a roguish man conduct...,"Directors:Victor Fleming, George Cukor, Sam Wood","Clark Gable, Vivien Leigh, Thomas Mitchell, Ba...","266,655",$198.68M
243,244.,It Happened One Night,(1934),105 min,"Comedy, Romance",8.1,A spoiled heiress running away from her family...,Frank Capra,"Clark Gable, Claudette Colbert, Walter Connoll...","85,644",$4.36M
244,245.,Sunrise: A Song of Two Humans,(1927),94 min,"Drama, Romance",8.1,An allegorical tale about a man fighting the g...,F.W. Murnau,"George O'Brien, Janet Gaynor, Margaret Livings...","43,811",None
245,246.,The General,(1926),67 min,"Action, Adventure, Comedy",8.1,When Union spies steal an engineer's beloved l...,"Directors:Clyde Bruckman, Buster Keaton","Buster Keaton, Marion Mack, Glen Cavender, Jim...","72,542",None
246,247.,Before Sunset,(2004),80 min,"Drama, Romance",8.0,"Nine years after Jesse and Celine first met, t...",Richard Linklater,"Ethan Hawke, Julie Delpy, Vernon Dobtcheff, Lo...","210,793",$5.82M
247,248.,"Monsters, Inc.",(2001),92 min,"Animation, Adventure, Comedy",8.0,"In order to power the city, monsters have to s...","Directors:Pete Docter, David Silverman, Lee Un...","Billy Crystal, John Goodman, Mary Gibbs, Steve...","748,975",$289.92M
248,249.,The Terminator,(1984),107 min,"Action, Sci-Fi",8.0,A seemingly indestructible robot is sent from ...,James Cameron,"Arnold Schwarzenegger, Linda Hamilton, Michael...","737,486",$38.40M
249,250.,Butch Cassidy and the Sundance Kid,(1969),110 min,"Biography, Crime, Drama",8.0,"Wyoming, early 1900s. Butch Cassidy and The Su...",George Roy Hill,"Paul Newman, Robert Redford, Katharine Ross, S...","189,015",$102.31M

In [116]:
#converting to csv files
data.to_csv(r'C:\Users\USER\Documents\Web_Scraping\data_250_movies.csv',index=False)